modLoader = "javafml"
loaderVersion = "[44,48)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "lifeleech"
version = "${version}"
displayName = "Life Leech Enchantment"
authors = "donmor"
description = '''
A Minecraft mod adding Life Leech enchantment. Restore HP on hitting your foes!
'''
itemIcon = "minecraft:enchanted_book"
updateJSONURL = "https://raw.githubusercontent.com/donmor/lifeleech/refs/heads/master/versions.json"
#logoFile = ""
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.lifeleech]]
modId = "forge"
mandatory = true
versionRange = "[44,48)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lifeleech]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.20.2)"
ordering = "NONE"
side = "BOTH"

[modproperties.lifeleech]
    catalogueImageIcon="assets/lifeleech/icon.png"
